import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import QueryClientProvider from 'papak/utils/QueryClientProvider';
import Footer from '@/components/common/Footer';
import Header from '@/components/common/Header';
import '../../globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// const inter = Inter({ subsets: ['latin'] });

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}
export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  return (
    <html dir="rtl">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      {/* <body className={inter.className}> */}
      <body className="flex min-h-screen flex-col">
        <AntdRegistry>
          <QueryClientProvider>
            <Header />
            <main className="grow">{children}</main>
            <Footer />
          </QueryClientProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
